server:
  port: 8080
  servlet:
    context-path: /
    encoding:
      charset: UTF-8
      enabled: true
      force: true

spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/security?serverTimezone=Asia/Seoul
    username: cos
    password: cos1234

  mvc:
    view:
      prefix: /templates/
      suffix: .mustache

  jpa:
    hibernate:
      ddl-auto: update # update none
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
    properties:
      hibernate:
        show_sql: true
        format_sql: true
        use_sql_comments: true

  security:
    oauth2:
      client:
        registration:
          google:
            client-id : 351036677214-vdk0mtun5cc4jn7ihdotuomc3b5bsg1d.apps.googleusercontent.com
            client-secret: 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
            scope:
            - email
            - profile
          facebook:
            client-id: 199699772173934
            client-secret: 56bd3c03ccc9944c16ffbaefddf6eb41
            scope:
              - email
              - public_profile
          naver:
            client-id: rmHkqg02zg9WEChyheFN
            client-secret: L_MDwp0J9S
            scope:
              - name
              - email
            client-name: Naver
            authorization-grant-type: authorization_code
            redirect-uri: http://localhost:8080/login/oauth2/code/naver

        provider:
          naver:
            authorization_uri: https://nid.naver.com/oauth2.0/authorize
            token_uri: https://nid.naver.com/oauth2.0/token
            user-info-uri: https://openapi.naver.com/v1/nid/me
            user_name_attribute: response #회원정보를 json으로 받는데 response라는 키값으로 네이버가 리턴해줌.

logging.level:
  org.hibernate.SQL: debug #sql 로그 레벨설정
  org.hibernate.type: trace #파라미터 보기위한 설정

